---
language: c

os: osx
compiler:
  - gcc

env:
  global:
    - CACHE="${HOME}/.local"
    - MPICH_VER="3.2.1"
    - MPICH_URL_HEAD="https://www.mpich.org/static/downloads/${MPICH_VER}"
    - MPICH_URL_TAIL="mpich-${MPICH_VER}.tar.gz"
    - MPICH_GCC6_BOT_URL_HEAD="https://github.com/sourceryinstitute/OpenCoarrays/files/1956499/"
    - MPICH_GCC7_BOT_URL_HEAD="https://github.com/sourceryinstitute/OpenCoarrays/files/1956441/"
    - MPICH_BOT_URL_TAIL="mpich-3.2.1_1.high_sierra.bottle.1.tar.gz"
    - BUILD_TYPES="Debug RelWithDebInfo Release CodeCoverage"
  # matrix:
  #   - GCC="6 7" OSX_PACKAGES="gcc@7 gcc@6 cmake shellcheck" BUILD_TYPE="cmake"

matrix:
  fast_finish: true
  include:
    - &macOS
      os: osx
      env:
        - BUILD_TYPE="InstallScript"
          GCC=8
          CC=clang
      addons:
        homebrew:
          packages:
            - shellcheck
            - cmake
            - mpich
          update: true
      compiler:
        - clang
    -
      <<: *macOS
      env:
        - GCC=8
          BUILD_TYPES="debug RelWithDebInfo Release"
          CC=gcc-8
      addons:
        homebrew:
          packages:
            - gcc
            - openmpi
            - shellcheck
            - cmake
          update: true
      compiler:
        - gcc

before_install: brew cask rm oclint
install: brew link gcc
script: ./test-script.cmake.sh
