language: generic
os: osx

matrix:
  include:
    - os: osx
      addons:
        homebrew:
          packages:
            - gcc
            - cmake
            - open-mpi
          update: true
    - os: osx
      addons:
        homebrew:
          packages:
            - gcc
            - cmake
            - mpich
          update: true


before_install: brew cask rm oclint
install: brew link gcc
before_script:
  - env | grep -i mpi || true
  - echo $PATH
  - env | grep -i cmake || true
  - ls "$(brew --prefix open-mpi)"/{bin,lib,include} || ls "$(brew --prefix mpich)"/{bin,lib,include} || true
script:
  - CC=gcc-8 CXX=g++-8 FC=gfortran-8 cmake --warn-uninitialized -DMPI_C_COMPILER=mpicc -DMPI_CXX_COMPILER=mpicxx .
  - ls -a CMakeFiles CMakeFiles/CMakeTmp
  - cat CMakeFiles/CMakeOutput.log
  - cmake --system-information
  - ls -a CMakeFiles/FindMPI
  - echo 'int main(){return 0;};' > zero.c
  - gcc-8 -o zero zero.c && ./zero
  - mpicc -o zero_mpi zero.c
  - mpirun -n 1 ./zero_mpi
  - mpirun -n 2 ./zero_mpi
  - ./zero_mpi
  - mpicc -o mpicworks "$(brew --prefix cmake)/share/cmake/Modules/FindMPI/test_mpi.c"
  - mpicc -DMPI_VERSION=3 -DMPI_SUBVERSION=1 -o mpicversion "$(brew --prefix cmake)/share/cmake/Modules/FindMPI/test_mpi.c"
  - mpirun -n 1 ./mpicworks
  - mpirun -n 1 ./mpicversion
  - mpirun -n 2 ./mpicworks
  - mpirun -n 2 ./mpicversion
  - ./mpicworks
  - ./mpicversion
