language: generic
os: osx

matrix:
  include:
    - os: osx
      addons:
        homebrew:
          packages:
            - gcc
            - cmake
            - open-mpi
          update: true
    - os: osx
      addons:
        homebrew:
          packages:
            - gcc
            - cmake
            - mpich
          update: true


before_install: brew cask rm oclint || true
install: brew link gcc
before_script:
  - env | grep -i mpi || true
  - echo $PATH
  - env | grep -i cmake || true
  - ls "$(brew --prefix open-mpi)"/{bin,lib,include} || ls "$(brew --prefix mpich)"/{bin,lib,include} || true
script:
  - FC=gfortran-8 CXX=g++-8 CC=gcc-8 cmake --debug-trycompile .
  - ls -a CMakeFiles CMakeFiles/CMakeTmp
  - cat CMakeFiles/CMake*.*
  - cat CMakeFiles/FindMPI || ls -a CMakeFiles/FindMPI
