language: generic
os: osx

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
            - gcc
            - cmake
            - open-mpi
          update: true
    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
            - gcc
            - cmake
            - mpich
          update: true

install:
  - brew install gcc || true
  - brew upgrade gcc || true
  - brew link --overwrite gcc || true
  - gcc-8 --version || true
  - gcc --version || true

script:
  - FC=gfortran-8 CXX=g++-8 CC=gcc-8 cmake -Wdev -Wdeprecated --debug-trycompile .
