---
language: generic

matrix:
  include:
    - os: osx
      addons:
        homebrew:
          packages:
            - gcc
            - cmake
            - open-mpi
          update: true
    - os: osx
      addons:
        homebrew:
          packages:
            - gcc
            - cmake
            - mpich
          update: true

before_install: brew cask rm oclint
install: brew link gcc
script: CC=gcc-8 cmake .
