language: generic
os: osx

matrix:
  include:
    - os: osx
      addons:
        homebrew:
          packages:
            - gcc
            - cmake
            - open-mpi
          update: true
    - os: osx
      addons:
        homebrew:
          packages:
            - gcc
            - cmake
            - mpich
          update: true


before_install: brew cask rm oclint
install: brew link gcc
before_script:
  - env | grep -i mpi || true
  - echo $PATH
  - env | grep -i cmake || true
  - ls "$(brew --prefix open-mpi)"/{bin,lib,include} || ls "$(brew --prefix mpich)"/{bin,lib,include} || true
script:
  - FC=gfortran-8 cmake --warn-uninitialized -DMPI_C_COMPILER=mpicc -DMPI_CXX_COMPILER=mpicxx .
  - ls -a CMakeFiles CMakeFiles/CMakeTmp
  - cat CMakeFiles/CMakeOutput.log
  - cmake --system-information
  - ls -a CMakeFiles/FindMPI
  - cat *.f90 *.cpp *.c *.log
